#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sisu-maven-plugin
Version  : 0.3.3
Release  : 2
URL      : https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-maven-plugin/0.3.3/sisu-maven-plugin-0.3.3.jar
Source0  : https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-maven-plugin/0.3.3/sisu-maven-plugin-0.3.3.jar
Source1  : https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-maven-plugin/0.3.3/sisu-maven-plugin-0.3.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : EPL-1.0
Requires: mvn-sisu-maven-plugin-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sisu-maven-plugin package.
Group: Data

%description data
data components for the mvn-sisu-maven-plugin package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-maven-plugin/0.3.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-maven-plugin/0.3.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-maven-plugin/0.3.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-maven-plugin/0.3.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-maven-plugin/0.3.3/sisu-maven-plugin-0.3.3.jar
/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-maven-plugin/0.3.3/sisu-maven-plugin-0.3.3.pom
